### ISSUE TITLE
Plugin Add error no www/main.js

### ISSUE THREAD

**Issue by Zssork** [MobisysGmbH/cordova-plugin-mlkit-barcode-scanner#9]
when using `cordova plugin add` i get the following error:

Failed to install 'cordova-plugin-mlkit-barcode-scanner': Error: Uh oh!
ENOENT: no such file or directory, open '/home/XYZ/Git/XYZ/plugins/cordova-plugin-mlkit-barcode-scanner/www/main.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at install (/home/XYZ/Git/XYZ/platforms/android/cordova/lib/pluginHandlers.js:162:36)
    at ActionStack.process (/home/XYZ/Git/XYZ/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/XYZ/Git/XYZ/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/home/XYZ/Git/XYZ/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:142:21)
    at /home/XYZ/Git/XYZ/platforms/android/cordova/Api.js:161:78
    at process._tickCallback (internal/process/next_tick.js:68:7)
Uh oh!
ENOENT: no such file or directory, open '/home/XYZ/Git/XYZ/plugins/cordova-plugin-mlkit-barcode-scanner/www/main.js'

**Comment by flobiwankenobi** [comment]
What's your full command?
Are you trying to add the git repository or a local copy?
Which version of this plugin was in use?
Info: Since 2.1.3 you have to build it first via `npm run build`
